config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'contacts', to: 'welcome#contacts'
  get 'about', to: 'welcome#about'
  get 'lol', to: 'welcome#lol'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def contacts
  end

  def about
  end

  def lol
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1 style="background-color: green">This is the about page</h1>

<%= link_to 'Home', root_path %>

app/views/welcome/contacts.html.erb
<h1 style="background-color: blue">This is the contacts page</h1>

<%= link_to 'Home', root_path %>

app/views/welcome/home.html.erb
<h1 style="background-color: red">This is the home page</h1>

<%= link_to 'About', about_path %>

<%= link_to 'Contacts', contacts_path %>

<% link_to 'Lol', lol_path %>

app/views/welcome/lol.html.erb
<h1 style="background-color: darkslategrey">This is the lol page</h1>

<%= link_to 'Home', root_path %>